### ISSUE TITLE
layer and attention are empty.

### ISSUE THREAD

**Issue by gogokre** [jessevig/bertviz#37]
I'm using colab but it doesn't work. Help.

%%javascript
require.config({
  paths: {
      d3: '//cdnjs.cloudflare.com/ajax/libs/d3/3.4.8/d3.min',
      jquery: '//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min',
  }
});

> def` show_head_view(model, tokenizer, sentence_a, sentence_b=None):

    inputs = tokenizer.encode_plus(sentence_a, sentence_b, return_tensors='pt', 

    add_special_tokens=True)

    input_ids = inputs['input_ids']
    if sentence_b:
        token_type_ids = inputs['token_type_ids']
        attention = model(input_ids, token_type_ids=token_type_ids)[-1]
        sentence_b_start = token_type_ids[0].tolist().index(1)
    else:
        attention = model(input_ids)[-1]
        sentence_b_start = None
    input_id_list = input_ids[0].tolist() # Batch index 0
    tokens = tokenizer.convert_ids_to_tokens(input_id_list)    
    head_view(attention, tokens, sentence_b_start)
model_version = 'bert-base-uncased'
do_lower_case = True

model = BertModel.from_pretrained(model_version, output_attentions=True)
tokenizer = BertTokenizer.from_pretrained(model_version, do_lower_case=do_lower_case)

sentence_a = "the cat sat on the mat"
sentence_b = "the cat lay on the rug"

show_head_view(model, tokenizer, sentence_a, sentence_b)

![capture](https://user-images.githubusercontent.com/44871498/74105682-62f1fd00-4ba3-11ea-8ba8-17ce2cda5121.PNG)

**Comment by jessevig** [comment]
Hi, thanks for filing this. What browser are you using? I've noticed intermittent issues like this with the Colabs, especially with Firefox. If you run that last step again, does it resolve?

**Comment by gogokre** [comment]
> Hi, thanks for filing this. What browser are you using? I've noticed intermittent issues like this with the Colabs, especially with Firefox. If you run that last step again, does it resolve?

빠른 답변 감사드립니다!.
저는 최신 버전의 구글 크롬을 사용하고 있는데도 같은 증상입니다..

**Comment by jessevig** [comment]
Okay, it looks like you may be running the standard Jupyter version of code? There is a special version of these notebooks for Colab. Are you able to access those Colab links from the README?

**Comment by WenTingTseng** [comment]
Hi, Did you solve this problem already?
I just resolved this
If you clone this to your local and use the Jupter Notebook by Anaconda and run this code. It will be fine.
Hope that helps you

**Comment by gogokre** [comment]
> Okay, it looks like you may be running the standard Jupyter version of code? There is a special version of these notebooks for Colab. Are you able to access those Colab links from the README?

Thank you for the answer! I tried the code of the link you mentioned, but it failed.
But using Jupter Notebook I succeeded.
Can I ask you one more thing?
sentence_a = sentence[0]
sentence_b = sentence[1]
I want to use it as above but if the sentence length is long, it doesn't print. Do you have any length restrictions?

**Comment by gogokre** [comment]
> Hi, Did you solve this problem already?
> I just resolved this
> If you clone this to your local and use the Jupter Notebook by Anaconda and run this code. It will be fine.
> Hope that helps you

Thank you very much. As you mentioned, I succeeded using Jupter Notebook.

**Comment by jessevig** [comment]
Thanks for the updates. Yes, there are some length restrictions though no precise limit. I updated the README accordingly for both issues. I hope to eventually improve the tool to support longer sentences as well.

**Comment by zhyq** [comment]
Hi,I just use Jupyter notebook by Anaconda, but still failed. I had fine tuned the model.

**Comment by jessevig** [comment]
Hi, are you able to run the notebook using a non-fine-tuned model?

**Comment by zhyq** [comment]
> Hi, are you able to run the notebook using a non-fine-tuned model?

Yes, I tried, but I still get the error

**Comment by jessevig** [comment]
Hi. So you are not able to run the existing notebooks successfully? Can you describe the error? Thanks.

**Comment by jlevy44** [comment]
I'm getting this issue as well. The layer tab is empty

**Comment by jessevig** [comment]
Hi, thanks for reporting this. Could you let me know:
1) Which notebook you are running (preferably including link to github repo to remove any ambiguity)
2) Whether you are running this in Colab or locally
3) Whether you modified it in any way
Thanks!
